---
- name: Configure Droplet on Ubuntu 22.04
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        update_cache: yes

    - name: Set up cron job for cleaning stale Docker images
      cron:
        name: "Docker image prune"
        minute: "0"
        hour: "5"
        job: "docker image prune --all --force"

    - name: Clone bash-alias-sync
      git:
        repo: https://github.com/Danand/bash-alias-sync.git
        dest: ~/bash-alias-sync
        clone: yes

    - name: Run install.sh script
      shell: |
        cd ~/bash-alias-sync
        chmod +x ./install.sh
        ./install.sh
